---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
       - name: gitlab
         image: gitlab/gitlab-ce:latest
         ports:
          - containerPort: 80
         env:
          - name: GITLAB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitlab-root-password
                key: password
---