# image code0ex/tp3_docker:latest
---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: tp3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp3-deployment
  namespace: tp3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp3
  template:
    metadata:
      labels:
        app: tp3
    spec:
      containers:
      - name: tp3
        image: code0ex/tp3_docker:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tp3-hpa
  namespace: tp3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tp3-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: tp3-service
  namespace: tp3
spec:
  type: LoadBalancer
  selector:
    app: tp3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
